[package]
name = "btc_collateral"
description = "Collaborative custody service for bitcoin collateralized loans"
version = "0.1.0"
edition = "2021"
keywords = ["bitcoin", "collateral", "btc", "rust"]
repository = "https://github.com/tvpeter/btc-collateral/"
license = "LICENSE.txt"
categories = ["asynchronous", "api-bindings", "web-programming::http-server"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = {version = "0.31.0", features = ["rand-std"]}
hex = "0.4.3"
