blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
edition = "2021"
fn_single_line = true
format_strings = true
group_imports = "StdExternalCrate"
hard_tabs = true
imports_granularity = "Module"
indent_style = "Block"
merge_derives = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
required_version = "1.6.0"
struct_field_align_threshold = 20
use_field_init_shorthand = true
version = "Two"
where_single_line = true
wrap_comments = true
